"""title

Revision ID: 2962a52b5877
Revises: 4f655b7c7b42
Create Date: 2017-08-19 21:06:33.718656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2962a52b5877'
down_revision = '4f655b7c7b42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('title', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'title')
    # ### end Alembic commands ###
