"""add ip

Revision ID: 307ba4e93a60
Revises: bbbb02ac04c6
Create Date: 2018-01-30 02:53:20.818701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '307ba4e93a60'
down_revision = 'bbbb02ac04c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ipaddresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ipaddr', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ipaddr')
    )
    op.create_table('postviews',
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('ipaddr_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ipaddr_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['ipaddresses.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('postviews')
    op.drop_table('ipaddresses')
    # ### end Alembic commands ###
