"""brief

Revision ID: 4f655b7c7b42
Revises: 616c9c54784c
Create Date: 2017-08-17 01:50:23.459602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f655b7c7b42'
down_revision = '616c9c54784c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_brief', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_brief')
    # ### end Alembic commands ###
