"""subject

Revision ID: 8887a5363962
Revises: 7b2832fd0571
Create Date: 2017-08-20 11:28:50.822025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8887a5363962'
down_revision = '7b2832fd0571'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('subject', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'subject')
    # ### end Alembic commands ###
